//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProSuite.DomainServices.AO.QA.HtmlReports {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HtmlReportResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HtmlReportResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProSuite.DomainServices.AO.QA.HtmlReports.HtmlReportResources", typeof(HtmlReportResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias.
        /// </summary>
        internal static string HtmlTexts_Alias {
            get {
                return ResourceManager.GetString("HtmlTexts_Alias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AOI buffer distance.
        /// </summary>
        internal static string HtmlTexts_AreaOfInterestBufferDistance {
            get {
                return ResourceManager.GetString("HtmlTexts_AreaOfInterestBufferDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AOI clip extent.
        /// </summary>
        internal static string HtmlTexts_AreaOfInterestClipExtent {
            get {
                return ResourceManager.GetString("HtmlTexts_AreaOfInterestClipExtent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AOI description.
        /// </summary>
        internal static string HtmlTexts_AreaOfInterestDescription {
            get {
                return ResourceManager.GetString("HtmlTexts_AreaOfInterestDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AOI feature source.
        /// </summary>
        internal static string HtmlTexts_AreaOfInterestFeatureSource {
            get {
                return ResourceManager.GetString("HtmlTexts_AreaOfInterestFeatureSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affected components.
        /// </summary>
        internal static string HtmlTexts_ColumnHeadingAffectedComponent {
            get {
                return ResourceManager.GetString("HtmlTexts_ColumnHeadingAffectedComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exceptions.
        /// </summary>
        internal static string HtmlTexts_ColumnHeadingExceptionCount {
            get {
                return ResourceManager.GetString("HtmlTexts_ColumnHeadingExceptionCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue count.
        /// </summary>
        internal static string HtmlTexts_ColumnHeadingIssueCount {
            get {
                return ResourceManager.GetString("HtmlTexts_ColumnHeadingIssueCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue description.
        /// </summary>
        internal static string HtmlTexts_ColumnHeadingIssueDescription {
            get {
                return ResourceManager.GetString("HtmlTexts_ColumnHeadingIssueDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string HtmlTexts_ColumnHeadingIssueType {
            get {
                return ResourceManager.GetString("HtmlTexts_ColumnHeadingIssueType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality condition.
        /// </summary>
        internal static string HtmlTexts_ColumnHeadingQualityCondition {
            get {
                return ResourceManager.GetString("HtmlTexts_ColumnHeadingQualityCondition", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Quality condition.
        /// </summary>
        internal static string HtmlTexts_ColumnHeadingQualityConditions {
	        get {
		        return ResourceManager.GetString("HtmlTexts_ColumnHeadingQualityConditions", resourceCulture);
	        }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dataset name.
        /// </summary>
        internal static string HtmlTexts_DatasetName {
            get {
                return ResourceManager.GetString("HtmlTexts_DatasetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dataset report.
        /// </summary>
        internal static string HtmlTexts_DatasetReport {
            get {
                return ResourceManager.GetString("HtmlTexts_DatasetReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data source.
        /// </summary>
        internal static string HtmlTexts_DataSource {
            get {
                return ResourceManager.GetString("HtmlTexts_DataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data sources.
        /// </summary>
        internal static string HtmlTexts_DataSources {
            get {
                return ResourceManager.GetString("HtmlTexts_DataSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of verification.
        /// </summary>
        internal static string HtmlTexts_DateOfVerification {
            get {
                return ResourceManager.GetString("HtmlTexts_DateOfVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string HtmlTexts_Description {
            get {
                return ResourceManager.GetString("HtmlTexts_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors.
        /// </summary>
        internal static string HtmlTexts_Errors {
            get {
                return ResourceManager.GetString("HtmlTexts_Errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature count.
        /// </summary>
        internal static string HtmlTexts_FeatureCount {
            get {
                return ResourceManager.GetString("HtmlTexts_FeatureCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feat. with non-linear Seg..
        /// </summary>
        internal static string HtmlTexts_FeaturesWithNonLinearSegments {
            get {
                return ResourceManager.GetString("HtmlTexts_FeaturesWithNonLinearSegments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features without geometry.
        /// </summary>
        internal static string HtmlTexts_FeaturesWithoutGeometry {
            get {
                return ResourceManager.GetString("HtmlTexts_FeaturesWithoutGeometry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geometry type.
        /// </summary>
        internal static string HtmlTexts_GeometryType {
            get {
                return ResourceManager.GetString("HtmlTexts_GeometryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue database.
        /// </summary>
        internal static string HtmlTexts_IssueDatabase {
            get {
                return ResourceManager.GetString("HtmlTexts_IssueDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map document.
        /// </summary>
        internal static string HtmlTexts_MapDocument {
            get {
                return ResourceManager.GetString("HtmlTexts_MapDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multipart features.
        /// </summary>
        internal static string HtmlTexts_MultipartFeatures {
            get {
                return ResourceManager.GetString("HtmlTexts_MultipartFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string HtmlTexts_Name {
            get {
                return ResourceManager.GetString("HtmlTexts_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string HtmlTexts_No {
            get {
                return ResourceManager.GetString("HtmlTexts_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;No category&gt;.
        /// </summary>
        internal static string HtmlTexts_NoCategory {
            get {
                return ResourceManager.GetString("HtmlTexts_NoCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to orig. path.
        /// </summary>
        internal static string HtmlTexts_OriginalPath {
            get {
                return ResourceManager.GetString("HtmlTexts_OriginalPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output directory.
        /// </summary>
        internal static string HtmlTexts_OutputDirectory {
            get {
                return ResourceManager.GetString("HtmlTexts_OutputDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing time.
        /// </summary>
        internal static string HtmlTexts_ProcessingTime {
            get {
                return ResourceManager.GetString("HtmlTexts_ProcessingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality Specification.
        /// </summary>
        internal static string HtmlTexts_QualitySpecificationTitle {
            get {
                return ResourceManager.GetString("HtmlTexts_QualitySpecificationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered as versioned.
        /// </summary>
        internal static string HtmlTexts_RegisteredAsVersioned {
            get {
                return ResourceManager.GetString("HtmlTexts_RegisteredAsVersioned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row count.
        /// </summary>
        internal static string HtmlTexts_RowCount {
            get {
                return ResourceManager.GetString("HtmlTexts_RowCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string HtmlTexts_Total {
            get {
                return ResourceManager.GetString("HtmlTexts_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string HtmlTexts_UndefinedExceptionCategory {
            get {
                return ResourceManager.GetString("HtmlTexts_UndefinedExceptionCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The verification was cancelled.
        /// </summary>
        internal static string HtmlTexts_VerificationCancelledMessage {
            get {
                return ResourceManager.GetString("HtmlTexts_VerificationCancelledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification report.
        /// </summary>
        internal static string HtmlTexts_VerificationReport {
            get {
                return ResourceManager.GetString("HtmlTexts_VerificationReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verified extent.
        /// </summary>
        internal static string HtmlTexts_VerifiedExtent {
            get {
                return ResourceManager.GetString("HtmlTexts_VerifiedExtent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version Name.
        /// </summary>
        internal static string HtmlTexts_VersionName {
            get {
                return ResourceManager.GetString("HtmlTexts_VersionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warnings.
        /// </summary>
        internal static string HtmlTexts_Warnings {
            get {
                return ResourceManager.GetString("HtmlTexts_Warnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordinate system.
        /// </summary>
        internal static string HtmlTexts_XYCoordinateSystem {
            get {
                return ResourceManager.GetString("HtmlTexts_XYCoordinateSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XY resolution.
        /// </summary>
        internal static string HtmlTexts_XYResolution {
            get {
                return ResourceManager.GetString("HtmlTexts_XYResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XY Tolerance.
        /// </summary>
        internal static string HtmlTexts_XYTolerance {
            get {
                return ResourceManager.GetString("HtmlTexts_XYTolerance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string HtmlTexts_Yes {
            get {
                return ResourceManager.GetString("HtmlTexts_Yes", resourceCulture);
            }
        }
    }
}
