//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProSuite.AGP.Editing.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizableStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizableStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProSuite.AGP.Editing.Properties.LocalizableStrings", typeof(LocalizableStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sketch the reshape line to change the selection.
        ///- Press R to restore the sketch from the previous reshape operation.
        ///- Press S to toggle the non-default reshape side of the geometry.
        ///- Press [ESC] to select different features..
        /// </summary>
        internal static string AdvancedReshapeTool_LogEnteringSketchMode {
            get {
                return ResourceManager.GetString("AdvancedReshapeTool_LogEnteringSketchMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select one or more line or polygon features to reshape. &lt;br&gt;- Press and hold SHIFT to add or remove features from the existing selection.&lt;br&gt;- Press and hold P to draw a polygon that completely contains the features to be selected. Finish the polygon with double-click.&lt;br&gt;- Press [O] for additional options.&lt;br&gt;{0}.
        /// </summary>
        internal static string AdvancedReshapeTool_LogPromptForSelection {
            get {
                return ResourceManager.GetString("AdvancedReshapeTool_LogPromptForSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Press Enter to re-use the existing selection..
        /// </summary>
        internal static string AdvancedReshapeTool_LogPromptForSelection_Enter {
            get {
                return ResourceManager.GetString("AdvancedReshapeTool_LogPromptForSelection_Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select one or more line or polygon features to cut along other feature(s).&lt;br&gt;- Press and hold SHIFT to add or remove features from the existing selection.&lt;br&gt;- Press and hold P to draw a polygon that completely contains the features to be selected. Finish the polygon with double-click..
        /// </summary>
        internal static string CutPolygonAlongTool_LogPromptForSelection {
            get {
                return ResourceManager.GetString("CutPolygonAlongTool_LogPromptForSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the target line or polygon features to use as cut line..
        /// </summary>
        internal static string CutPolygonAlongTool_LogUsingCurrentSelection {
            get {
                return ResourceManager.GetString("CutPolygonAlongTool_LogUsingCurrentSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sketch a hole or any polygon to be erased from the selection.&lt;br&gt;Press [ESC] to reselect the polygon(s)..
        /// </summary>
        internal static string EraseTool_LogEnteringSketchMode {
            get {
                return ResourceManager.GetString("EraseTool_LogEnteringSketchMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select one or more features.&lt;br&gt;- Press and hold SHIFT to add or remove features from the existing selection.&lt;br&gt;- Press and hold P to draw a polygon that completely contains the features to be selected. Finish the polygon with double-click..
        /// </summary>
        internal static string EraseTool_LogPromptForSelection {
            get {
                return ResourceManager.GetString("EraseTool_LogPromptForSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a polygon that contains a hole or several polygons with a gap in between..
        /// </summary>
        internal static string FillHoleTool_LogPromptForSelection {
            get {
                return ResourceManager.GetString("FillHoleTool_LogPromptForSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select one or more polygon features which contain the hole(s) to be removed..
        /// </summary>
        internal static string RemoveHoleTool_LogPromptForSelection {
            get {
                return ResourceManager.GetString("RemoveHoleTool_LogPromptForSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}&lt;br&gt;Press [ESC] to select one or more different features..
        /// </summary>
        internal static string RemoveOverlapsTool_AfterSelection {
            get {
                return ResourceManager.GetString("RemoveOverlapsTool_AfterSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Overlaps.
        /// </summary>
        internal static string RemoveOverlapsTool_Caption {
            get {
                return ResourceManager.GetString("RemoveOverlapsTool_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select one or more line or polygon features from which a part should be removed.&lt;br&gt;- Press and hold SHIFT to add or remove features from the existing selection.&lt;br&gt;- Press and hold P to draw a polygon that completely contains the features to be selected. Finish the polygon with double-click..
        /// </summary>
        internal static string RemoveOverlapsTool_LogPromptForSelection {
            get {
                return ResourceManager.GetString("RemoveOverlapsTool_LogPromptForSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove a part of a feature that overlaps with other polygon features..
        /// </summary>
        internal static string RemoveOverlapsTool_Message {
            get {
                return ResourceManager.GetString("RemoveOverlapsTool_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select one or more line or polygon features to align with other feature(s). &lt;br&gt;- Press and hold SHIFT to add or remove features from the existing selection. &lt;br&gt;- Press and hold P to draw a polygon that completely contains the features to be selected. Finish the polygon with double-click..
        /// </summary>
        internal static string ReshapeAlongTool_LogPromptForSelection {
            get {
                return ResourceManager.GetString("ReshapeAlongTool_LogPromptForSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the target line or polygon features to align with. &lt;br&gt;- Press [ESC] to select a different feature..
        /// </summary>
        internal static string ReshapeAlongTool_LogUsingCurrentSelection {
            get {
                return ResourceManager.GetString("ReshapeAlongTool_LogUsingCurrentSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select one or more features by clicking or dragging a box:
        ///- Press and hold SHIFT to add or remove features from the existing selection.
        ///- Press CTRL and drag a box to show a list of selectable feature classes.
        ///- Press ALT and click to select all features at the click point..
        /// </summary>
        internal static string SelectionTool_LogPromptForSelection {
            get {
                return ResourceManager.GetString("SelectionTool_LogPromptForSelection", resourceCulture);
            }
        }
    }
}
