//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProSuite.AGP.Editing.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProSuite.AGP.Editing.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AdvancedReshapeToolCursor {
            get {
                object obj = ResourceManager.GetObject("AdvancedReshapeToolCursor", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AdvancedReshapeToolCursorShift {
            get {
                object obj = ResourceManager.GetObject("AdvancedReshapeToolCursorShift", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CrackerToolCursor {
            get {
                object obj = ResourceManager.GetObject("CrackerToolCursor", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CrackerToolCursorProcess {
            get {
                object obj = ResourceManager.GetObject("CrackerToolCursorProcess", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CrackerToolCursorShift {
            get {
                object obj = ResourceManager.GetObject("CrackerToolCursorShift", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CreateFeatureInPickedClassCursor {
            get {
                object obj = ResourceManager.GetObject("CreateFeatureInPickedClassCursor", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CutPolygonAlongTool {
            get {
                object obj = ResourceManager.GetObject("CutPolygonAlongTool", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CutPolygonAlongToolCursor {
            get {
                object obj = ResourceManager.GetObject("CutPolygonAlongToolCursor", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CutPolygonAlongToolCursorProcess {
            get {
                object obj = ResourceManager.GetObject("CutPolygonAlongToolCursorProcess", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CutPolygonAlongToolCursorShift {
            get {
                object obj = ResourceManager.GetObject("CutPolygonAlongToolCursorShift", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DestroyAndRebuildToolCursor {
            get {
                object obj = ResourceManager.GetObject("DestroyAndRebuildToolCursor", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] EditSketchCrosshair {
            get {
                object obj = ResourceManager.GetObject("EditSketchCrosshair", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] EraseToolCursor {
            get {
                object obj = ResourceManager.GetObject("EraseToolCursor", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] EraseToolCursorShift {
            get {
                object obj = ResourceManager.GetObject("EraseToolCursorShift", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FillHoleToolCursor {
            get {
                object obj = ResourceManager.GetObject("FillHoleToolCursor", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FillHoleToolCursorProcess {
            get {
                object obj = ResourceManager.GetObject("FillHoleToolCursorProcess", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FillHoleToolCursorShift {
            get {
                object obj = ResourceManager.GetObject("FillHoleToolCursorShift", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PolygonDrawerCursor {
            get {
                object obj = ResourceManager.GetObject("PolygonDrawerCursor", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RemoveHoleToolCursor {
            get {
                object obj = ResourceManager.GetObject("RemoveHoleToolCursor", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RemoveHoleToolCursorProcess {
            get {
                object obj = ResourceManager.GetObject("RemoveHoleToolCursorProcess", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RemoveHoleToolCursorShift {
            get {
                object obj = ResourceManager.GetObject("RemoveHoleToolCursorShift", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RemoveOverlapsToolCursor {
            get {
                object obj = ResourceManager.GetObject("RemoveOverlapsToolCursor", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RemoveOverlapsToolCursorProcess {
            get {
                object obj = ResourceManager.GetObject("RemoveOverlapsToolCursorProcess", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RemoveOverlapsToolCursorShift {
            get {
                object obj = ResourceManager.GetObject("RemoveOverlapsToolCursorShift", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ReshapeAlongToolCursor {
            get {
                object obj = ResourceManager.GetObject("ReshapeAlongToolCursor", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ReshapeAlongToolCursorProcess {
            get {
                object obj = ResourceManager.GetObject("ReshapeAlongToolCursorProcess", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ReshapeAlongToolCursorProcessShift {
            get {
                object obj = ResourceManager.GetObject("ReshapeAlongToolCursorProcessShift", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ReshapeAlongToolCursorShift {
            get {
                object obj = ResourceManager.GetObject("ReshapeAlongToolCursorShift", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SelectionToolNormal {
            get {
                object obj = ResourceManager.GetObject("SelectionToolNormal", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SelectionToolNormalShift {
            get {
                object obj = ResourceManager.GetObject("SelectionToolNormalShift", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SelectionToolOriginal {
            get {
                object obj = ResourceManager.GetObject("SelectionToolOriginal", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SelectionToolOriginalShift {
            get {
                object obj = ResourceManager.GetObject("SelectionToolOriginalShift", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SelectionToolUser {
            get {
                object obj = ResourceManager.GetObject("SelectionToolUser", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SelectionToolUserShift {
            get {
                object obj = ResourceManager.GetObject("SelectionToolUserShift", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
