// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: verify_quality.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace ProSuite.ProtobufClasses {
  public static partial class VerifyQualityService
  {
    static readonly string __ServiceName = "ProSuite.ProtobufClasses.VerifyQualityService";

    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    static readonly grpc::Marshaller<global::ProSuite.ProtobufClasses.VerifyQualityRequest> __Marshaller_ProSuite_ProtobufClasses_VerifyQualityRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::ProSuite.ProtobufClasses.VerifyQualityRequest.Parser));
    static readonly grpc::Marshaller<global::ProSuite.ProtobufClasses.VerifyQualityResponse> __Marshaller_ProSuite_ProtobufClasses_VerifyQualityResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::ProSuite.ProtobufClasses.VerifyQualityResponse.Parser));

    static readonly grpc::Method<global::ProSuite.ProtobufClasses.VerifyQualityRequest, global::ProSuite.ProtobufClasses.VerifyQualityResponse> __Method_PerformQualityVerification = new grpc::Method<global::ProSuite.ProtobufClasses.VerifyQualityRequest, global::ProSuite.ProtobufClasses.VerifyQualityResponse>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "PerformQualityVerification",
        __Marshaller_ProSuite_ProtobufClasses_VerifyQualityRequest,
        __Marshaller_ProSuite_ProtobufClasses_VerifyQualityResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::ProSuite.ProtobufClasses.VerifyQualityReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of VerifyQualityService</summary>
    [grpc::BindServiceMethod(typeof(VerifyQualityService), "BindService")]
    public abstract partial class VerifyQualityServiceBase
    {
      public virtual global::System.Threading.Tasks.Task PerformQualityVerification(global::ProSuite.ProtobufClasses.VerifyQualityRequest request, grpc::IServerStreamWriter<global::ProSuite.ProtobufClasses.VerifyQualityResponse> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for VerifyQualityService</summary>
    public partial class VerifyQualityServiceClient : grpc::ClientBase<VerifyQualityServiceClient>
    {
      /// <summary>Creates a new client for VerifyQualityService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public VerifyQualityServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for VerifyQualityService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public VerifyQualityServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected VerifyQualityServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected VerifyQualityServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual grpc::AsyncServerStreamingCall<global::ProSuite.ProtobufClasses.VerifyQualityResponse> PerformQualityVerification(global::ProSuite.ProtobufClasses.VerifyQualityRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return PerformQualityVerification(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncServerStreamingCall<global::ProSuite.ProtobufClasses.VerifyQualityResponse> PerformQualityVerification(global::ProSuite.ProtobufClasses.VerifyQualityRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_PerformQualityVerification, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override VerifyQualityServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new VerifyQualityServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(VerifyQualityServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_PerformQualityVerification, serviceImpl.PerformQualityVerification).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, VerifyQualityServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_PerformQualityVerification, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::ProSuite.ProtobufClasses.VerifyQualityRequest, global::ProSuite.ProtobufClasses.VerifyQualityResponse>(serviceImpl.PerformQualityVerification));
    }

  }
}
#endregion
