//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProSuite.DomainServices.AO.QA.Issues {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class IssueTableFieldAliases {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IssueTableFieldAliases() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProSuite.DomainServices.AO.QA.Issues.IssueTableFieldAliases", typeof(IssueTableFieldAliases).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affected component.
        /// </summary>
        internal static string AffectedComponent {
            get {
                return ResourceManager.GetString("AffectedComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception Category.
        /// </summary>
        internal static string ExceptionCategory {
            get {
                return ResourceManager.GetString("ExceptionCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception definition date.
        /// </summary>
        internal static string ExceptionDefinitionDate {
            get {
                return ResourceManager.GetString("ExceptionDefinitionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Managed exception import origin.
        /// </summary>
        internal static string ExceptionImportOrigin {
            get {
                return ResourceManager.GetString("ExceptionImportOrigin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception revision date.
        /// </summary>
        internal static string ExceptionLastRevisionDate {
            get {
                return ResourceManager.GetString("ExceptionLastRevisionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Managed exception UUID.
        /// </summary>
        internal static string ExceptionLineageUuid {
            get {
                return ResourceManager.GetString("ExceptionLineageUuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception notes.
        /// </summary>
        internal static string ExceptionNotes {
            get {
                return ResourceManager.GetString("ExceptionNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception origin.
        /// </summary>
        internal static string ExceptionOrigin {
            get {
                return ResourceManager.GetString("ExceptionOrigin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception retirement date.
        /// </summary>
        internal static string ExceptionRetirementDate {
            get {
                return ResourceManager.GetString("ExceptionRetirementDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception shape match criterion.
        /// </summary>
        internal static string ExceptionShapeMatchCriterion {
            get {
                return ResourceManager.GetString("ExceptionShapeMatchCriterion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception status.
        /// </summary>
        internal static string ExceptionStatus {
            get {
                return ResourceManager.GetString("ExceptionStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Managed exception version begin date.
        /// </summary>
        internal static string ExceptionVersionBeginDate {
            get {
                return ResourceManager.GetString("ExceptionVersionBeginDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Managed exception version end date.
        /// </summary>
        internal static string ExceptionVersionEndDate {
            get {
                return ResourceManager.GetString("ExceptionVersionEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Managed exception version import origin.
        /// </summary>
        internal static string ExceptionVersionImportOrigin {
            get {
                return ResourceManager.GetString("ExceptionVersionImportOrigin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Managed exception version import status.
        /// </summary>
        internal static string ExceptionVersionImportStatus {
            get {
                return ResourceManager.GetString("ExceptionVersionImportStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Managed exception version UUID.
        /// </summary>
        internal static string ExceptionVersionUuid {
            get {
                return ResourceManager.GetString("ExceptionVersionUuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exported exception: OID.
        /// </summary>
        internal static string ExportedExceptionOID {
            get {
                return ResourceManager.GetString("ExportedExceptionOID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exported exception: reported by verified origin.
        /// </summary>
        internal static string ExportedExceptionReportedByVerifiedOrigin {
            get {
                return ResourceManager.GetString("ExportedExceptionReportedByVerifiedOrigin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exported exception: number of matched issues.
        /// </summary>
        internal static string ExportedExceptionUsageCount {
            get {
                return ResourceManager.GetString("ExportedExceptionUsageCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Involved objects.
        /// </summary>
        internal static string InvolvedObjects {
            get {
                return ResourceManager.GetString("InvolvedObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is stop condition.
        /// </summary>
        internal static string IsStopCondition {
            get {
                return ResourceManager.GetString("IsStopCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue assignment.
        /// </summary>
        internal static string IssueAssignment {
            get {
                return ResourceManager.GetString("IssueAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue code.
        /// </summary>
        internal static string IssueCode {
            get {
                return ResourceManager.GetString("IssueCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue code description.
        /// </summary>
        internal static string IssueCodeDescription {
            get {
                return ResourceManager.GetString("IssueCodeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue description.
        /// </summary>
        internal static string IssueDescription {
            get {
                return ResourceManager.GetString("IssueDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue severity.
        /// </summary>
        internal static string IssueSeverity {
            get {
                return ResourceManager.GetString("IssueSeverity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numeric value 1.
        /// </summary>
        internal static string NumericValue1 {
            get {
                return ResourceManager.GetString("NumericValue1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numeric value 2.
        /// </summary>
        internal static string NumericValue2 {
            get {
                return ResourceManager.GetString("NumericValue2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality condition.
        /// </summary>
        internal static string QualityCondition {
            get {
                return ResourceManager.GetString("QualityCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality condition UUID.
        /// </summary>
        internal static string QualityConditionUuid {
            get {
                return ResourceManager.GetString("QualityConditionUuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality condition version UUID.
        /// </summary>
        internal static string QualityConditionVersionUuid {
            get {
                return ResourceManager.GetString("QualityConditionVersionUuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test description.
        /// </summary>
        internal static string TestDescription {
            get {
                return ResourceManager.GetString("TestDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test name.
        /// </summary>
        internal static string TestName {
            get {
                return ResourceManager.GetString("TestName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test type.
        /// </summary>
        internal static string TestType {
            get {
                return ResourceManager.GetString("TestType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text value.
        /// </summary>
        internal static string TextValue {
            get {
                return ResourceManager.GetString("TextValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url.
        /// </summary>
        internal static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }
    }
}
