//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProSuite.DomainModel.AO.QA.SpecificationReport {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SpecificationReportResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SpecificationReportResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProSuite.DomainModel.AO.QA.SpecificationReport.SpecificationReportResources", typeof(SpecificationReportResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string HtmlTexts_Category {
            get {
                return ResourceManager.GetString("HtmlTexts_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data model.
        /// </summary>
        internal static string HtmlTexts_ColumnHeaderDataModel {
            get {
                return ResourceManager.GetString("HtmlTexts_ColumnHeaderDataModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string HtmlTexts_ColumnHeaderDescription {
            get {
                return ResourceManager.GetString("HtmlTexts_ColumnHeaderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter expression.
        /// </summary>
        internal static string HtmlTexts_ColumnHeaderFilterExpression {
            get {
                return ResourceManager.GetString("HtmlTexts_ColumnHeaderFilterExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Code.
        /// </summary>
        internal static string HtmlTexts_ColumnHeaderIssueCode {
            get {
                return ResourceManager.GetString("HtmlTexts_ColumnHeaderIssueCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Type.
        /// </summary>
        internal static string HtmlTexts_ColumnHeaderIssueType {
            get {
                return ResourceManager.GetString("HtmlTexts_ColumnHeaderIssueType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter.
        /// </summary>
        internal static string HtmlTexts_ColumnHeaderParameter {
            get {
                return ResourceManager.GetString("HtmlTexts_ColumnHeaderParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality Condition.
        /// </summary>
        internal static string HtmlTexts_ColumnHeaderQualityCondition {
            get {
                return ResourceManager.GetString("HtmlTexts_ColumnHeaderQualityCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference data.
        /// </summary>
        internal static string HtmlTexts_ColumnHeaderReferenceData {
            get {
                return ResourceManager.GetString("HtmlTexts_ColumnHeaderReferenceData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality conditions based on this test.
        /// </summary>
        internal static string HtmlTexts_ColumnHeaderReferencingQualityCondition {
            get {
                return ResourceManager.GetString("HtmlTexts_ColumnHeaderReferencingQualityCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string HtmlTexts_ColumnHeaderType {
            get {
                return ResourceManager.GetString("HtmlTexts_ColumnHeaderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string HtmlTexts_ColumnHeaderValue {
            get {
                return ResourceManager.GetString("HtmlTexts_ColumnHeaderValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contents.
        /// </summary>
        internal static string HtmlTexts_ContentsTitle {
            get {
                return ResourceManager.GetString("HtmlTexts_ContentsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data model.
        /// </summary>
        internal static string HtmlTexts_DataModel {
            get {
                return ResourceManager.GetString("HtmlTexts_DataModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string HtmlTexts_Description {
            get {
                return ResourceManager.GetString("HtmlTexts_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Implementation.
        /// </summary>
        internal static string HtmlTexts_Implementation {
            get {
                return ResourceManager.GetString("HtmlTexts_Implementation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Involved Datasets.
        /// </summary>
        internal static string HtmlTexts_InvolvedDatasetsTitle {
            get {
                return ResourceManager.GetString("HtmlTexts_InvolvedDatasetsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string HtmlTexts_No {
            get {
                return ResourceManager.GetString("HtmlTexts_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality conditions.
        /// </summary>
        internal static string HtmlTexts_QualityConditionsTitle {
            get {
                return ResourceManager.GetString("HtmlTexts_QualityConditionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        internal static string HtmlTexts_Test {
            get {
                return ResourceManager.GetString("HtmlTexts_Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Categories.
        /// </summary>
        internal static string HtmlTexts_TestCategories {
            get {
                return ResourceManager.GetString("HtmlTexts_TestCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Description.
        /// </summary>
        internal static string HtmlTexts_TestDescription {
            get {
                return ResourceManager.GetString("HtmlTexts_TestDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Signature.
        /// </summary>
        internal static string HtmlTexts_TestSignature {
            get {
                return ResourceManager.GetString("HtmlTexts_TestSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tests.
        /// </summary>
        internal static string HtmlTexts_TestsTitle {
            get {
                return ResourceManager.GetString("HtmlTexts_TestsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        internal static string HtmlTexts_Url {
            get {
                return ResourceManager.GetString("HtmlTexts_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UUID.
        /// </summary>
        internal static string HtmlTexts_Uuid {
            get {
                return ResourceManager.GetString("HtmlTexts_Uuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version UUID.
        /// </summary>
        internal static string HtmlTexts_VersionUuid {
            get {
                return ResourceManager.GetString("HtmlTexts_VersionUuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string HtmlTexts_Yes {
            get {
                return ResourceManager.GetString("HtmlTexts_Yes", resourceCulture);
            }
        }
    }
}
