//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProSuite.Commons.AO.Properties {
	/// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizableStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizableStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProSuite.Commons.AO.Properties.LocalizableStrings", typeof(LocalizableStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The adjusting polyline is contained by the target point tolerance buffer. Such situations are not adjustable..
        /// </summary>
        internal static string AdjustGeometry_AdjustImpossible {
            get {
                return ResourceManager.GetString("AdjustGeometry_AdjustImpossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking geometries....
        /// </summary>
        internal static string AdjustGeometry_CheckGeometries {
            get {
                return ResourceManager.GetString("AdjustGeometry_CheckGeometries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The creation of the tolerance buffer has failed..
        /// </summary>
        internal static string AdjustGeometry_CreateToleranceError {
            get {
                return ResourceManager.GetString("AdjustGeometry_CreateToleranceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating tolerance buffer....
        /// </summary>
        internal static string AdjustGeometry_CreatingTolerance {
            get {
                return ResourceManager.GetString("AdjustGeometry_CreatingTolerance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geometry may not be empty at GetCentroid.
        /// </summary>
        internal static string AdjustGeometry_CurveEmpty {
            get {
                return ResourceManager.GetString("AdjustGeometry_CurveEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curve may not be zero length at GetCentroid.
        /// </summary>
        internal static string AdjustGeometry_CurveLenghtZero {
            get {
                return ResourceManager.GetString("AdjustGeometry_CurveLenghtZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geometry type not supported: {0}, {1}.
        /// </summary>
        internal static string AdjustGeometry_GeometryTypeNotSupported {
            get {
                return ResourceManager.GetString("AdjustGeometry_GeometryTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geometry may not be null at GetCentroid.
        /// </summary>
        internal static string AdjustGeometry_GetCentroidGeometryNull {
            get {
                return ResourceManager.GetString("AdjustGeometry_GetCentroidGeometryNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Geometry has to be a Polygon or Polyline..
        /// </summary>
        internal static string AdjustGeometry_InvalidInput {
            get {
                return ResourceManager.GetString("AdjustGeometry_InvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not access open island geometry..
        /// </summary>
        internal static string AdjustGeometry_InvalidOpenIsland {
            get {
                return ResourceManager.GetString("AdjustGeometry_InvalidOpenIsland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geometries of type other than Polygon/Line/Multi-/Point are not adjustable..
        /// </summary>
        internal static string AdjustGeometry_InvalidSelection {
            get {
                return ResourceManager.GetString("AdjustGeometry_InvalidSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The difference of the adjust geometry with the target geometry is more than one single part. Adjusting is not possible..
        /// </summary>
        internal static string AdjustGeometry_MultiPartDifference {
            get {
                return ResourceManager.GetString("AdjustGeometry_MultiPartDifference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected feature can not be adjusted to multiple targets.&lt;br&gt;(Not all of the target geometries cross the tolerance buffer)&lt;br&gt;Please change the tolerance..
        /// </summary>
        internal static string AdjustGeometry_MultipleTargetsNoCross {
            get {
                return ResourceManager.GetString("AdjustGeometry_MultipleTargetsNoCross", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-perpendicular adjust may not be used with multiple disjoined targets..
        /// </summary>
        internal static string AdjustGeometry_MultipleTargetsNonperpendicular {
            get {
                return ResourceManager.GetString("AdjustGeometry_MultipleTargetsNonperpendicular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tolerance is too big for adjusting to more than one disjoint target.&lt;br&gt;(The selected object is completely inside the tolerance).
        /// </summary>
        internal static string AdjustGeometry_MultipleTargetsSourceInside {
            get {
                return ResourceManager.GetString("AdjustGeometry_MultipleTargetsSourceInside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected target is a multipoint geometry. Adjusting is not possible. Please select a target geometry with a different type than multipoint..
        /// </summary>
        internal static string AdjustGeometry_MultiPointSelected {
            get {
                return ResourceManager.GetString("AdjustGeometry_MultiPointSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nearest point to source of closed line part is not inside adjusting area..
        /// </summary>
        internal static string AdjustGeometry_NearestOutsideArea {
            get {
                return ResourceManager.GetString("AdjustGeometry_NearestOutsideArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No cutting points with the centroid line found..
        /// </summary>
        internal static string AdjustGeometry_NoCuttingPoints {
            get {
                return ResourceManager.GetString("AdjustGeometry_NoCuttingPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No maximal distance point found..
        /// </summary>
        internal static string AdjustGeometry_NoMaxPoint {
            get {
                return ResourceManager.GetString("AdjustGeometry_NoMaxPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geometries do not overlap. Non Perpendicual adjusting is not possible..
        /// </summary>
        internal static string AdjustGeometry_NoOverlap {
            get {
                return ResourceManager.GetString("AdjustGeometry_NoOverlap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not all point Z-values are NaN free after trim..
        /// </summary>
        internal static string AdjustGeometry_NotNaNFree {
            get {
                return ResourceManager.GetString("AdjustGeometry_NotNaNFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open island target consist of {0} parts.
        /// </summary>
        internal static string AdjustGeometry_OpenIslandMultipart {
            get {
                return ResourceManager.GetString("AdjustGeometry_OpenIslandMultipart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one adjusted target part found in open island geometry, adjusting not possible. Please change the tolerance..
        /// </summary>
        internal static string AdjustGeometry_OpenIslandMultipartTarget {
            get {
                return ResourceManager.GetString("AdjustGeometry_OpenIslandMultipartTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjusting geometry is outside tolerance..
        /// </summary>
        internal static string AdjustGeometry_OutsideTolerance {
            get {
                return ResourceManager.GetString("AdjustGeometry_OutsideTolerance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjusting geometry....
        /// </summary>
        internal static string AdjustGeometry_ProgressInfo {
            get {
                return ResourceManager.GetString("AdjustGeometry_ProgressInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geometries are being adjusted. This might take a few moments..
        /// </summary>
        internal static string AdjustGeometry_SlowProgressInfo {
            get {
                return ResourceManager.GetString("AdjustGeometry_SlowProgressInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trimmer geometry union threw an exception..
        /// </summary>
        internal static string AdjustGeometry_TrimmerUnionException {
            get {
                return ResourceManager.GetString("AdjustGeometry_TrimmerUnionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tolerance trimming of adjusted geometry was not valid..
        /// </summary>
        internal static string AdjustGeometry_TrimmingInvalid {
            get {
                return ResourceManager.GetString("AdjustGeometry_TrimmingInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsure adjusting situation. Result could be invalid..
        /// </summary>
        internal static string AdjustGeometry_UnsureResult {
            get {
                return ResourceManager.GetString("AdjustGeometry_UnsureResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not access Z value for point. Keeping actual value..
        /// </summary>
        internal static string AdjustGeometry_ZNotReadable {
            get {
                return ResourceManager.GetString("AdjustGeometry_ZNotReadable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surface is not defined.
        /// </summary>
        internal static string ApplyZ_NoSurface {
            get {
                return ResourceManager.GetString("ApplyZ_NoSurface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For the given geometry type [{0}] a surface can not be used to assign Z..
        /// </summary>
        internal static string ApplyZ_NoSurfaceUsed {
            get {
                return ResourceManager.GetString("ApplyZ_NoSurfaceUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZMode is unknown..
        /// </summary>
        internal static string ApplyZServices_UnknownZMode {
            get {
                return ResourceManager.GetString("ApplyZServices_UnknownZMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApplyZ was not successful. Modified geometry is invalid..
        /// </summary>
        internal static string ApplyZServices_Unsuccessful {
            get {
                return ResourceManager.GetString("ApplyZServices_Unsuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The polygon has identical rings.
        /// </summary>
        internal static string GeometryUtils_IsGeometrySimple_IdenticalRings {
            get {
                return ResourceManager.GetString("GeometryUtils_IsGeometrySimple_IdenticalRings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geometry is not simple (duplicate points).
        /// </summary>
        internal static string GeometryUtils_NonSimpleReason_DuplicatePoints {
            get {
                return ResourceManager.GetString("GeometryUtils_NonSimpleReason_DuplicatePoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The geometry contains an empty part.
        /// </summary>
        internal static string GeometryUtils_NonSimpleReason_EmptyPart {
            get {
                return ResourceManager.GetString("GeometryUtils_NonSimpleReason_EmptyPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The geometry has rings that are not oriented correctly (outer rings - clockwise, inner rings - counter-clockwise).
        /// </summary>
        internal static string GeometryUtils_NonSimpleReason_RingOrientation {
            get {
                return ResourceManager.GetString("GeometryUtils_NonSimpleReason_RingOrientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The geometry has segments that are not consistently oriented. The &apos;to&apos; point of a segment should be coincident with the &apos;from&apos; point of the next segment..
        /// </summary>
        internal static string GeometryUtils_NonSimpleReason_SegmentOrientation {
            get {
                return ResourceManager.GetString("GeometryUtils_NonSimpleReason_SegmentOrientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The geometry has self intersections.
        /// </summary>
        internal static string GeometryUtils_NonSimpleReason_SelfIntersections {
            get {
                return ResourceManager.GetString("GeometryUtils_NonSimpleReason_SelfIntersections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The geometry has self intersections but this is valid for non-planar lines.
        /// </summary>
        internal static string GeometryUtils_NonSimpleReason_SelfIntersections_Allowed {
            get {
                return ResourceManager.GetString("GeometryUtils_NonSimpleReason_SelfIntersections_Allowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The geometry has segments that are shorter than allowed by the tolerance.
        /// </summary>
        internal static string GeometryUtils_NonSimpleReason_ShortSegments {
            get {
                return ResourceManager.GetString("GeometryUtils_NonSimpleReason_ShortSegments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The geometry has an unclosed ring.
        /// </summary>
        internal static string GeometryUtils_NonSimpleReason_UnclosedRing {
            get {
                return ResourceManager.GetString("GeometryUtils_NonSimpleReason_UnclosedRing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geometry is not simple.
        /// </summary>
        internal static string GeometryUtils_NonSimpleReason_Unknown {
            get {
                return ResourceManager.GetString("GeometryUtils_NonSimpleReason_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username and/or password is invalid.
        /// </summary>
        internal static string WorkspaceUtils_Exception_InvalidUserNameOrPassword {
            get {
                return ResourceManager.GetString("WorkspaceUtils_Exception_InvalidUserNameOrPassword", resourceCulture);
            }
        }
    }
}
