//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProSuite.QA.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizableStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizableStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProSuite.QA.Tests.Properties.LocalizableStrings", typeof(LocalizableStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constraint is not fulfilled ({0}).
        /// </summary>
        internal static string EdgeMatchUtils_AttributeConstraints_ConstraintNotFulfilled {
            get {
                return ResourceManager.GetString("EdgeMatchUtils_AttributeConstraints_ConstraintNotFulfilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values are not equal ({0}).
        /// </summary>
        internal static string EdgeMatchUtils_AttributeConstraints_ValuesNotEqual {
            get {
                return ResourceManager.GetString("EdgeMatchUtils_AttributeConstraints_ValuesNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A matching neighbor feature exists (common boundary length: {0}). {1}..
        /// </summary>
        internal static string QaEdgeMatchBorderingLines_Match_ConstraintsNotFulfilled {
            get {
                return ResourceManager.GetString("QaEdgeMatchBorderingLines_Match_ConstraintsNotFulfilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A matching neighbor feature exists, but a line end point is not coincident..
        /// </summary>
        internal static string QaEdgeMatchBorderingLines_Match_EndPointNotCoincident {
            get {
                return ResourceManager.GetString("QaEdgeMatchBorderingLines_Match_EndPointNotCoincident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No exact match. A nearby neighbor feature connected to the border exists. The borders are not coincident where the lines touch their border..
        /// </summary>
        internal static string QaEdgeMatchBorderingLines_NoMatch_CandidateExists {
            get {
                return ResourceManager.GetString("QaEdgeMatchBorderingLines_NoMatch_CandidateExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No nearby neighbor feature connected to the border exists..
        /// </summary>
        internal static string QaEdgeMatchBorderingLines_NoMatch_NoCandidate {
            get {
                return ResourceManager.GetString("QaEdgeMatchBorderingLines_NoMatch_NoCandidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The border line is partly outside the verified extent..
        /// </summary>
        internal static string QaEdgeMatchBorderingLines_PartlyOutsideVerifiedExtent {
            get {
                return ResourceManager.GetString("QaEdgeMatchBorderingLines_PartlyOutsideVerifiedExtent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borders are not coincident..
        /// </summary>
        internal static string QaEdgeMatchBorderingPoints_BordersNotCoincident {
            get {
                return ResourceManager.GetString("QaEdgeMatchBorderingPoints_BordersNotCoincident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No exact match. A nearby neighbor feature connected to the border exists (distance: {0})..
        /// </summary>
        internal static string QaEdgeMatchBorderingPoints_NoMatch_CandidateExists {
            get {
                return ResourceManager.GetString("QaEdgeMatchBorderingPoints_NoMatch_CandidateExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No neighboring border point found within search distance..
        /// </summary>
        internal static string QaEdgeMatchBorderingPoints_NoMatch_NoCandidate {
            get {
                return ResourceManager.GetString("QaEdgeMatchBorderingPoints_NoMatch_NoCandidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A matching neighbor feature exists (common boundary length: {0}). {1}..
        /// </summary>
        internal static string QaEdgeMatchCrossingAreas_Match_ConstraintsNotFulfilled {
            get {
                return ResourceManager.GetString("QaEdgeMatchCrossingAreas_Match_ConstraintsNotFulfilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No exact match. A nearby neighbor feature connected to the border exists. Borders are not coincident..
        /// </summary>
        internal static string QaEdgeMatchCrossingAreas_NoMatch_CandidateExists {
            get {
                return ResourceManager.GetString("QaEdgeMatchCrossingAreas_NoMatch_CandidateExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No nearby neighbor feature connected to the border exists..
        /// </summary>
        internal static string QaEdgeMatchCrossingAreas_NoMatch_NoCandidate {
            get {
                return ResourceManager.GetString("QaEdgeMatchCrossingAreas_NoMatch_NoCandidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The border line is partly outside the verified extent..
        /// </summary>
        internal static string QaEdgeMatchCrossingAreas_PartlyOutsideVerifiedExtent {
            get {
                return ResourceManager.GetString("QaEdgeMatchCrossingAreas_PartlyOutsideVerifiedExtent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borders are not coincident..
        /// </summary>
        internal static string QaEdgeMatchCrossingLines_BordersNotCoincident {
            get {
                return ResourceManager.GetString("QaEdgeMatchCrossingLines_BordersNotCoincident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No exact match. Nearby feature connected to the border exists, nearest end point on border: {0}..
        /// </summary>
        internal static string QaEdgeMatchCrossingLines_NoMatch_CandidateExists {
            get {
                return ResourceManager.GetString("QaEdgeMatchCrossingLines_NoMatch_CandidateExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No exact match. Nearby feature connected to the border exists, nearest end point on border: {0} (too far). Distance to neighbor line: {1}..
        /// </summary>
        internal static string QaEdgeMatchCrossingLines_NoMatch_CandidateExists_EndPointOutsideTolerance {
            get {
                return ResourceManager.GetString("QaEdgeMatchCrossingLines_NoMatch_CandidateExists_EndPointOutsideTolerance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No nearby neighbor feature connected to the border exists..
        /// </summary>
        internal static string QaEdgeMatchCrossingLines_NoMatch_NoCandidate {
            get {
                return ResourceManager.GetString("QaEdgeMatchCrossingLines_NoMatch_NoCandidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No nearby neighbor feature connected to the border exists. The end point connects to another feature on the same side..
        /// </summary>
        internal static string QaEdgeMatchCrossingLines_NoMatch_NoCandidate_ConnectedOnSameSide {
            get {
                return ResourceManager.GetString("QaEdgeMatchCrossingLines_NoMatch_NoCandidate_ConnectedOnSameSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part not near reference.
        /// </summary>
        internal static string QaFullCoincidence_PartNotNearReference {
            get {
                return ResourceManager.GetString("QaFullCoincidence_PartNotNearReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constraint is not fulfilled for geometry part: {0} ({1}).
        /// </summary>
        internal static string QaGeometryConstraint_ConstraintNotFulfilled_ForShapePart {
            get {
                return ResourceManager.GetString("QaGeometryConstraint_ConstraintNotFulfilled_ForShapePart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constraint is not fulfilled for shape: {0} ({1}).
        /// </summary>
        internal static string QaGeometryConstraint_QaGeometryConstraint_ConstraintNotFulfilled_ForShape {
            get {
                return ResourceManager.GetString("QaGeometryConstraint_QaGeometryConstraint_ConstraintNotFulfilled_ForShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part within near distance of {0} is {1} long (&gt; {2}).
        /// </summary>
        internal static string QaNearCoincidenceBase_NearlyCoincidentSection_Extended_Base {
            get {
                return ResourceManager.GetString("QaNearCoincidenceBase_NearlyCoincidentSection_Extended_Base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ; the paths are connected.
        /// </summary>
        internal static string QaNearCoincidenceBase_NearlyCoincidentSection_Extended_ConnectedPaths {
            get {
                return ResourceManager.GetString("QaNearCoincidenceBase_NearlyCoincidentSection_Extended_ConnectedPaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ; the closest distance is {0}.
        /// </summary>
        internal static string QaNearCoincidenceBase_NearlyCoincidentSection_Extended_DisjointPaths {
            get {
                return ResourceManager.GetString("QaNearCoincidenceBase_NearlyCoincidentSection_Extended_DisjointPaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part near {0} &gt; {1}.
        /// </summary>
        internal static string QaNearCoincidenceBase_NearlyCoincidentSection_Short {
            get {
                return ResourceManager.GetString("QaNearCoincidenceBase_NearlyCoincidentSection_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gap found ( area: .
        /// </summary>
        internal static string QaNoGaps_GapFound {
            get {
                return ResourceManager.GetString("QaNoGaps_GapFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ; perimeter * perimeter / area: {0}; perimeter: {1}.
        /// </summary>
        internal static string QaNoGaps_SliverParameters {
            get {
                return ResourceManager.GetString("QaNoGaps_SliverParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias name &apos;{0}&apos; must be different from field name &apos;{1}&apos;.
        /// </summary>
        internal static string QaSchemaFieldAliases_EqualsFieldName {
            get {
                return ResourceManager.GetString("QaSchemaFieldAliases_EqualsFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias name &apos;{0}&apos; must not differ only in character case from field name &apos;{1}&apos;.
        /// </summary>
        internal static string QaSchemaFieldAliases_EqualsFieldNameExceptCase {
            get {
                return ResourceManager.GetString("QaSchemaFieldAliases_EqualsFieldNameExceptCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field alias name &apos;{0}&apos; (field &apos;{1}&apos;): {2}.
        /// </summary>
        internal static string QaSchemaFieldAliases_FieldNameCase {
            get {
                return ResourceManager.GetString("QaSchemaFieldAliases_FieldNameCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias name &apos;{0}&apos; must be equal to field name for system field &apos;{1}&apos;.
        /// </summary>
        internal static string QaSchemaFieldAliases_MustBeEqualToFieldName {
            get {
                return ResourceManager.GetString("QaSchemaFieldAliases_MustBeEqualToFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &apos;{0}&apos; has no alias name.
        /// </summary>
        internal static string QaSchemaFieldAliases_NoAliasName {
            get {
                return ResourceManager.GetString("QaSchemaFieldAliases_NoAliasName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias name &apos;{0}&apos; in table &apos;{1}&apos; is not unique. The following fields have the same alias name: {2}.
        /// </summary>
        internal static string QaSchemaFieldAliases_NotUnique {
            get {
                return ResourceManager.GetString("QaSchemaFieldAliases_NotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain &apos;{0}&apos;: {1} (&apos;{2}&apos;).
        /// </summary>
        internal static string QaSchemaFieldDomainDescriptions_DomainDescriptionInvalidLength {
            get {
                return ResourceManager.GetString("QaSchemaFieldDomainDescriptions_DomainDescriptionInvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain description &apos;{0}&apos; is not unique. The following domains have the same description: {1}.
        /// </summary>
        internal static string QaSchemaFieldDomainDescriptions_DomainDescriptionNotUnique {
            get {
                return ResourceManager.GetString("QaSchemaFieldDomainDescriptions_DomainDescriptionNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following field names are not unique on the first {0} characters: {1}.
        /// </summary>
        internal static string QaSchemaFieldNames_FieldNamesSubstringNotUnique {
            get {
                return ResourceManager.GetString("QaSchemaFieldNames_FieldNamesSubstringNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordinate system is different (expected: {0} actual: {1}); .
        /// </summary>
        internal static string QaSchemaSpatialReference_CoordinateSystemDifferent {
            get {
                return ResourceManager.GetString("QaSchemaSpatialReference_CoordinateSystemDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M domain/precision is different (expected: {0} actual: {1}); .
        /// </summary>
        internal static string QaSchemaSpatialReference_MDomainOrPrecisionDifferent {
            get {
                return ResourceManager.GetString("QaSchemaSpatialReference_MDomainOrPrecisionDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MMin: {0} MMax: {1} M Resolution: {2}.
        /// </summary>
        internal static string QaSchemaSpatialReference_MPrecision {
            get {
                return ResourceManager.GetString("QaSchemaSpatialReference_MPrecision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M tolerance is different (expected: {0} actual: {1}); .
        /// </summary>
        internal static string QaSchemaSpatialReference_MToleranceDifferent {
            get {
                return ResourceManager.GetString("QaSchemaSpatialReference_MToleranceDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;not defined&gt;.
        /// </summary>
        internal static string QaSchemaSpatialReference_NotDefined {
            get {
                return ResourceManager.GetString("QaSchemaSpatialReference_NotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical coordinate system is different (expected: {0} actual: {1}); .
        /// </summary>
        internal static string QaSchemaSpatialReference_VerticalCoordinateSystemDifferent {
            get {
                return ResourceManager.GetString("QaSchemaSpatialReference_VerticalCoordinateSystemDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XY domain/precision is different (expected: {0} actual: {1}); .
        /// </summary>
        internal static string QaSchemaSpatialReference_XYDomainOrPrecisionDifferent {
            get {
                return ResourceManager.GetString("QaSchemaSpatialReference_XYDomainOrPrecisionDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XMin: {0} YMin: {1} XMax: {2} YMax: {3} XY Resolution: {4}.
        /// </summary>
        internal static string QaSchemaSpatialReference_XYPrecision {
            get {
                return ResourceManager.GetString("QaSchemaSpatialReference_XYPrecision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XY tolerance is different (expected: {0} actual: {1}); .
        /// </summary>
        internal static string QaSchemaSpatialReference_XYToleranceDifferent {
            get {
                return ResourceManager.GetString("QaSchemaSpatialReference_XYToleranceDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z domain/precision is different (expected: {0} actual: {1}); .
        /// </summary>
        internal static string QaSchemaSpatialReference_ZDomainOrPrecisionDifferent {
            get {
                return ResourceManager.GetString("QaSchemaSpatialReference_ZDomainOrPrecisionDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZMin: {0} ZMax: {1} Z Resolution: {2}.
        /// </summary>
        internal static string QaSchemaSpatialReference_ZPrecision {
            get {
                return ResourceManager.GetString("QaSchemaSpatialReference_ZPrecision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z tolerance is different (expected: {0} actual: {1}); .
        /// </summary>
        internal static string QaSchemaSpatialReference_ZToleranceDifferent {
            get {
                return ResourceManager.GetString("QaSchemaSpatialReference_ZToleranceDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geometry is empty.
        /// </summary>
        internal static string QaSimpleGeometry_Empty {
            get {
                return ResourceManager.GetString("QaSimpleGeometry_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geometry is null.
        /// </summary>
        internal static string QaSimpleGeometry_Null {
            get {
                return ResourceManager.GetString("QaSimpleGeometry_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ring classified as sliver (area: {1}; perimeter * perimeter / area: {2}; perimeter: {3}).
        /// </summary>
        internal static string QaSliverPolygon_Message {
            get {
                return ResourceManager.GetString("QaSliverPolygon_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coincident section found.
        /// </summary>
        internal static string QaTopoNotNear_CoincidentSectionFound {
            get {
                return ResourceManager.GetString("QaTopoNotNear_CoincidentSectionFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inconsistent line symbol end (end segment is too short compared to the symbol width).
        /// </summary>
        internal static string QaTopoNotNear_InconsistentLineSymbolEnd {
            get {
                return ResourceManager.GetString("QaTopoNotNear_InconsistentLineSymbolEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part within near distance is {0} long (&gt;= {1}); the paths are connected.
        /// </summary>
        internal static string QaTopoNotNear_NearlyCoincidentSection_Connected {
            get {
                return ResourceManager.GetString("QaTopoNotNear_NearlyCoincidentSection_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected segments within near distance form a loop.
        /// </summary>
        internal static string QaTopoNotNear_NearlyCoincidentSection_Connected_Loop {
            get {
                return ResourceManager.GetString("QaTopoNotNear_NearlyCoincidentSection_Connected_Loop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected segments form a loop and are within near distance to other connected segments.
        /// </summary>
        internal static string QaTopoNotNear_NearlyCoincidentSection_Connected_Loop_WithinNear {
            get {
                return ResourceManager.GetString("QaTopoNotNear_NearlyCoincidentSection_Connected_Loop_WithinNear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part within near distance is {0} long (&gt;= {1}); the paths are crossing but not connected.
        /// </summary>
        internal static string QaTopoNotNear_NearlyCoincidentSection_Crossing {
            get {
                return ResourceManager.GetString("QaTopoNotNear_NearlyCoincidentSection_Crossing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part within near distance is {0} long (&gt;= {1}); the paths are disjoint.
        /// </summary>
        internal static string QaTopoNotNear_NearlyCoincidentSection_Disjoint {
            get {
                return ResourceManager.GetString("QaTopoNotNear_NearlyCoincidentSection_Disjoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segments are fully within near distance of other segments.
        /// </summary>
        internal static string QaTopoNotNear_NearlyCoincidentSection_WithinNear {
            get {
                return ResourceManager.GetString("QaTopoNotNear_NearlyCoincidentSection_WithinNear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segments are fully within near distance of other segments to which they are connected.
        /// </summary>
        internal static string QaTopoNotNear_NearlyCoincidentSection_WithinNear_Connected {
            get {
                return ResourceManager.GetString("QaTopoNotNear_NearlyCoincidentSection_WithinNear_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature with unconnected ends is too short: {0}.
        /// </summary>
        internal static string QaTopoNotNear_ShortSubpart {
            get {
                return ResourceManager.GetString("QaTopoNotNear_ShortSubpart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid string value in field {0}: {1} ({2}).
        /// </summary>
        internal static string QaTrimmedTextFields_InvalidStringValue {
            get {
                return ResourceManager.GetString("QaTrimmedTextFields_InvalidStringValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value in field {0} contains only blanks ({1} blank{2}).
        /// </summary>
        internal static string QaTrimmedTextFields_ValueContainsOnlyBlanks {
            get {
                return ResourceManager.GetString("QaTrimmedTextFields_ValueContainsOnlyBlanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value in field {0} has both leading and trailing blanks ({1} blanks).
        /// </summary>
        internal static string QaTrimmedTextFields_ValueHasLeadingAndTrailingBlanks {
            get {
                return ResourceManager.GetString("QaTrimmedTextFields_ValueHasLeadingAndTrailingBlanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value in field {0} has {1} leading blank{2}.
        /// </summary>
        internal static string QaTrimmedTextFields_ValueHasLeadingBlank {
            get {
                return ResourceManager.GetString("QaTrimmedTextFields_ValueHasLeadingBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value in field {0} has {1} trailing blank{2}.
        /// </summary>
        internal static string QaTrimmedTextFields_ValueHasTrailingBlank {
            get {
                return ResourceManager.GetString("QaTrimmedTextFields_ValueHasTrailingBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be all lowercase: {1}.
        /// </summary>
        internal static string SchemaTestUtils_CaseAllLowercase {
            get {
                return ResourceManager.GetString("SchemaTestUtils_CaseAllLowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be all uppercase: {1}.
        /// </summary>
        internal static string SchemaTestUtils_CaseAllUppercase {
            get {
                return ResourceManager.GetString("SchemaTestUtils_CaseAllUppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be mixed case: {1}.
        /// </summary>
        internal static string SchemaTestUtils_CaseMixedCase {
            get {
                return ResourceManager.GetString("SchemaTestUtils_CaseMixedCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must not be all-lower case: {1}.
        /// </summary>
        internal static string SchemaTestUtils_CaseNotAllLowercase {
            get {
                return ResourceManager.GetString("SchemaTestUtils_CaseNotAllLowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must not be all-upper case: {1}.
        /// </summary>
        internal static string SchemaTestUtils_CaseNotAllUppercase {
            get {
                return ResourceManager.GetString("SchemaTestUtils_CaseNotAllUppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length of {0} is greater than maximum length {1}: {2}.
        /// </summary>
        internal static string SchemaTestUtils_LengthGreaterThanMaximum {
            get {
                return ResourceManager.GetString("SchemaTestUtils_LengthGreaterThanMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length of {0} is less than minimum length {1}: {2}.
        /// </summary>
        internal static string SchemaTestUtils_LengthLessThanMinimum {
            get {
                return ResourceManager.GetString("SchemaTestUtils_LengthLessThanMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nearby edge does not pass through vertex (distance to edge: {0}).
        /// </summary>
        internal static string VertexCoincidenceChecker_NearbyEdgeNotPassingThroughVertex_DifferentFeature {
            get {
                return ResourceManager.GetString("VertexCoincidenceChecker_NearbyEdgeNotPassingThroughVertex_DifferentFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to . Vertex: {0}, {1}.
        /// </summary>
        internal static string VertexCoincidenceChecker_NearbyEdgeNotPassingThroughVertex_ReportCoordinatesSuffix {
            get {
                return ResourceManager.GetString("VertexCoincidenceChecker_NearbyEdgeNotPassingThroughVertex_ReportCoordinatesSuffi" +
                        "x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nearby edge on same feature does not pass through vertex (distance to edge: {0}).
        /// </summary>
        internal static string VertexCoincidenceChecker_NearbyEdgeNotPassingThroughVertex_SameFeature {
            get {
                return ResourceManager.GetString("VertexCoincidenceChecker_NearbyEdgeNotPassingThroughVertex_SameFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nearby vertex is not coincident (distance: {0}).
        /// </summary>
        internal static string VertexCoincidenceChecker_NearbyVertexNotCoincident_DifferentFeature {
            get {
                return ResourceManager.GetString("VertexCoincidenceChecker_NearbyVertexNotCoincident_DifferentFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to . Vertex: {0}, {1}; nearby vertex: {2}, {3}.
        /// </summary>
        internal static string VertexCoincidenceChecker_NearbyVertexNotCoincident_ReportCoordinatesSuffix {
            get {
                return ResourceManager.GetString("VertexCoincidenceChecker_NearbyVertexNotCoincident_ReportCoordinatesSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nearby vertex on same feature is not coincident (distance: {0}).
        /// </summary>
        internal static string VertexCoincidenceChecker_NearbyVertexNotCoincident_SameFeature {
            get {
                return ResourceManager.GetString("VertexCoincidenceChecker_NearbyVertexNotCoincident_SameFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nearby edge does not have a coincident vertex (distance to edge: {0}).
        /// </summary>
        internal static string VertexCoincidenceChecker_NoVertexOnNearbyEdge_DifferentFeature {
            get {
                return ResourceManager.GetString("VertexCoincidenceChecker_NoVertexOnNearbyEdge_DifferentFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to . Vertex: {0}, {1}.
        /// </summary>
        internal static string VertexCoincidenceChecker_NoVertexOnNearbyEdge_ReportCoordinatesSuffix {
            get {
                return ResourceManager.GetString("VertexCoincidenceChecker_NoVertexOnNearbyEdge_ReportCoordinatesSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nearby edge on same feature does not have a coincident vertex (distance to edge: {0}).
        /// </summary>
        internal static string VertexCoincidenceChecker_NoVertexOnNearbyEdge_SameFeature {
            get {
                return ResourceManager.GetString("VertexCoincidenceChecker_NoVertexOnNearbyEdge_SameFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z of coincident point on edge differs (Z difference: {0}).
        /// </summary>
        internal static string VertexCoincidenceChecker_ZDifference_CoincidentEdge_DifferentFeature {
            get {
                return ResourceManager.GetString("VertexCoincidenceChecker_ZDifference_CoincidentEdge_DifferentFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z of coincident point on edge of same feature differs (Z difference: {0}).
        /// </summary>
        internal static string VertexCoincidenceChecker_ZDifference_CoincidentEdge_SameFeature {
            get {
                return ResourceManager.GetString("VertexCoincidenceChecker_ZDifference_CoincidentEdge_SameFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z of coincident vertex differs (Z difference: {0}).
        /// </summary>
        internal static string VertexCoincidenceChecker_ZDifference_CoincidentVertex_DifferentFeature {
            get {
                return ResourceManager.GetString("VertexCoincidenceChecker_ZDifference_CoincidentVertex_DifferentFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z of coincident vertex on same feature differs (Z difference: {0}).
        /// </summary>
        internal static string VertexCoincidenceChecker_ZDifference_CoincidentVertex_SameFeature {
            get {
                return ResourceManager.GetString("VertexCoincidenceChecker_ZDifference_CoincidentVertex_SameFeature", resourceCulture);
            }
        }
    }
}
