//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProSuite.QA.Tests.Documentation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DocIfStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DocIfStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProSuite.QA.Tests.Documentation.DocIfStrings", typeof(DocIfStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters all issues, if &apos;Filter&apos; = true (default). If &apos;Filter&apos; = false, no issue is filtered.
        /// </summary>
        public static string IfAll_0 {
            get {
                return ResourceManager.GetString("IfAll_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if true (default): filter all issues
        ///if false: filter no issues.
        /// </summary>
        public static string IfAll_Filter {
            get {
                return ResourceManager.GetString("IfAll_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters issues that intersect any feature in a &apos;featureClass&apos;.
        /// </summary>
        public static string IfIntersecting_0 {
            get {
                return ResourceManager.GetString("IfIntersecting_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to point, multipoint, polyline or polygon feature class.
        /// </summary>
        public static string IfIntersecting_featureClass {
            get {
                return ResourceManager.GetString("IfIntersecting_featureClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters issues where any involved row fulfills &apos;constraint&apos;.
        /// </summary>
        public static string IfInvolvedRows_0 {
            get {
                return ResourceManager.GetString("IfInvolvedRows_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to constraint .
        /// </summary>
        public static string IfInvolvedRows_constraint {
            get {
                return ResourceManager.GetString("IfInvolvedRows_constraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of tables, to which a involved row must belong to, to be checked.
        ///If not specified, all involved rows are check for the constraint.
        /// </summary>
        public static string IfInvolvedRows_Tables {
            get {
                return ResourceManager.GetString("IfInvolvedRows_Tables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters issues that are completely near any feature of &apos;featureClass&apos;.
        /// </summary>
        public static string IfNear_0 {
            get {
                return ResourceManager.GetString("IfNear_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polyline or polygon feature class.
        /// </summary>
        public static string IfNear_featureClass {
            get {
                return ResourceManager.GetString("IfNear_featureClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance.
        /// </summary>
        public static string IfNear_near {
            get {
                return ResourceManager.GetString("IfNear_near", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters issues that are completely within any feature in a &apos;featureClass&apos;.
        /// </summary>
        public static string IfWithin_0 {
            get {
                return ResourceManager.GetString("IfWithin_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to point, multipoint, polyline or polygon feature class.
        /// </summary>
        public static string IfWithin_featureClass {
            get {
                return ResourceManager.GetString("IfWithin_featureClass", resourceCulture);
            }
        }
    }
}
